all:
	npx firebase login
	npx firebase functions:config:get > cicumikuji-config.json
	@echo "\nNext step:"
	@echo "Please download your service key from https://console.firebase.google.com/project/cicumikuji/settings/serviceaccounts/adminsdk and store it as cicumikuji-firebase-adminsdk.json"